name: matrix

on: push

jobs:
  gen:
    runs-on: ubuntu-latest
    outputs:
      prind: ${{ steps.prind.outputs.prind }}
    steps:
      - uses: actions/checkout@v4
      - id: prind
        run: echo "prind=$(jq -c < output.json)" >> "$GITHUB_OUTPUT"
  
  matrix:
    runs-on: ubuntu-latest
    needs: gen
    strategy:
      matrix: ${{ fromJSON(needs.gen.outputs.prind) }}
    steps:
      - run: echo ${{ matrix.services.context }} ${{ matrix.services.target }} ${{ matrix.services.repo }} ${{ matrix.services.version }} ${{ matrix.platform }}