name: matrix

on: push

jobs:
  gen:
    runs-on: ubuntu-latest
    outputs:
      prind: ${{ steps.prind.outputs.prind }}
    steps:
      - uses: actions/checkout@v4
      - id: prind
        run: echo "prind=$(cat output.json)" >> "$GITHUB_OUTPUT"
  
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: ${{ fromJSON(needs.gen.outputs.prind) }}
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64/v8
    steps:
      - run: printenv