name: matrix

on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "prind=$(cat output.json)" >> "$GITHUB_OUTPUT"
  
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: ${{ fromJSON(needs.define-matrix.outputs.prind) }}
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64/v8
    steps:
      - run: printenv