name: build-and-push

on: push

jobs:
  gen:
    runs-on: ubuntu-latest
    outputs:
      prind: ${{ steps.prind.outputs.prind }}
    steps:
      - uses: actions/checkout@v4
      - id: prind
        run: echo "prind=$(jq -c < output.json)" >> "$GITHUB_OUTPUT"
  
  build:
    runs-on: ubuntu-latest
    needs:
      - gen
    strategy:
      matrix: ${{ fromJSON(needs.gen.outputs.prind) }}
    steps:
      - run: echo ${{ matrix.build.context }} ${{ matrix.build.targets }} ${{ matrix.build.repo }} ${{ matrix.build.versions }} ${{ matrix.platforms }}

  # push:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   strategy:
  #     matrix: